package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.GitHubIssueTracker
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.githubIssues
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    check(archived == false) {
        "Unexpected archived: '$archived'"
    }
    archived = true

    features {
        val feature1 = find<GitHubIssueTracker> {
            githubIssues {
                id = "SrgUtils__IssueTracker"
                displayName = "MinecraftForge/SrgUtils"
                repositoryURL = "https://github.com/MinecraftForge/SrgUtils"
            }
        }
        feature1.apply {
        }
    }
}
